name: 'Update ClickUp status'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: npm install
        run: npm i @actions/core @actions/github

      - name: Checks the PR title
        run: node ./scripts/action.js
