name: 'Update ClickUp status'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checks the PR title
        run: node ./scripts/action.js
