name: 'Update ClickUp status'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    using: 'node20'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm i @actions/core @actions/github

      - name: Checks the PR title
        run: node ./scripts/action.js
